### ISSUE TITLE
Chrome behat runs crashing

### ISSUE THREAD

**Issue by danpoltawski** [danpoltawski/docker-moodle#12]
As discovered by Eloy: 
https://pastebin.com/3NUAjbmn

I haven't really looked into chrome or even using a named tag, so needs some work.

**Comment by stronk7** [comment]
I'm running here behat + chrome using tagged selenium/standalone-chrome:2.53.1-beryllium

Already @ 13000 and progressing (all the crashes I experimented were before that point).

Cross your fingers. Will report.

**Comment by stronk7** [comment]
Grrr, failed too, just a thousand later (@ 14000): https://pastebin.com/N0Hk7iwJ

Trying selenium/standalone-chrome:3.0.1 now that is the recommended one @ [Docs](https://docs.moodle.org/dev/Acceptance_testing/Browsers/Working_combinations_of_OS%2BBrowser%2Bselenium)

**Comment by stronk7** [comment]
A curiosity that I just observed... is that it seems that every "F" in the process leads to one of the runs to stop. So, in the example above... the run (4 parallel) dies when the 4th failure happens.

Current run here with 3.0.1 has had already a couple of "F" and I can see that there are only 2 remaining chrome instances in the server, so I bet the will die sooner or later (already @ 13000).

**Comment by stronk7** [comment]
And here there are the results... https://pastebin.com/0jRaDyqh

As said, each of the 4 parallel go dying... and then the 3 reruns catch and execute practically everything 1by1 (no parallelism)... just guessing if the problem maybe concurrency in parallel and we need to launch separated seleniums or something like that.

**Comment by danpoltawski** [comment]
Trying to replicate now with standalone-chrome:3.0.1

**Comment by stronk7** [comment]
I'm running here without parallelism (same docker instances than previous run - selechrome 3.0.1). Just to see if it also crashes or not.

**Comment by danpoltawski** [comment]
(I get the same results, to confirm)

**Comment by stronk7** [comment]
lalala, and also happens with non-parallel. pity (3.0.1). It all went ok till 18000 and then, the 1st failure ended killing the run (and re-run#1 started).

Curiously re-run#1 broke exactly in the same "point" and then re-run#2 started (I configured it for 3 re-runs). Maybe the exact test is important as far as it seems to be a constant one (maybe no, it just called my attention).

Link: https://pastebin.com/97UQvfPm

**Comment by stronk7** [comment]
Just for the records, with `-v /dev/shm:/dev/shm`aka:

```
   selenium:
-    image: selenium/standalone-chrome
+    volumes:
+      - /dev/shm:/dev/shm
```

It ended ok! https://pastebin.com/DzsVfjLA (there were 2 failures, but that's unrelated) It ended in 2h without ugly crashes!

Source: https://github.com/SeleniumHQ/docker-selenium#running-the-images (there is also another tip to be used with FF there).

**Comment by danpoltawski** [comment]
Fancy preparing a pull request?
