### ISSUE TITLE
Use depends_on to add a dependency in web for db

### ISSUE THREAD

**Issue by scara** [danpoltawski/docker-moodle#5]
A small cleanup: see more at https://docs.docker.com/compose/compose-file/compose-file-v2/#dependson, including https://docs.docker.com/compose/startup-order/ if you want to be sure that any _db_ will be [available](https://github.com/vishnubob/wait-for-it/blob/8f52a814ef0cc70820b87fbf888273f3aa7f5a9b/wait-for-it.sh), not only [mssql](https://github.com/danpoltawski/moodle-db-mssql/blob/39a246aaec31011eff97acf9c786035070c74e72/root/wait-for-mssql-to-come-up.sh).

**Comment by danpoltawski** [comment]
Thanks Matteo, I agree that adding the dependencies is worth it for db. I think i avoided doing that initially because in my initial iterations were multiple dbs to a single webserver. 

> if you want to be sure that any db will be available, not only mssql.

Are you refffering to the tests? Because apart from the tests - mssql is not determined to be up. Its just for determining when to run the sql command to populate the data.

**Comment by danpoltawski** [comment]
Closing this as done in d176995

**Comment by scara** [comment]
TNX, 👍.
About your commit message, I eventually agree: "readiness" should be check in a different way.

It's worth noting that `healthcheck` ([v2.1](https://docs.docker.com/compose/compose-file/compose-file-v2/#healthcheck)) is not as good as it could appear since it doesn't take care of the "_readiness_" so in case of e.g. a slow service startup (e.g. _solr_) you should alter `retries` to give it the proper time to start i.e. useless for probe actual health but to put a working `service_healthy` condition under `depends_on`.

Better to add, in a separate issue if you still like the idea, an ad-hoc _readiness_ check (tipically, 1s loop) in the/a docker entrypoint of those images for each of the dependencies declared here in the compose - worth noting that this area should be better covered by _docker_, if used as the sole orchestration tool.

TIA,
Matteo
